### ISSUE TITLE
Display characters in overview table

### ISSUE THREAD

**Issue by supernoir** [supernoir/app_imaginaryfriends#2]

**Comment by supernoir** [comment]
@stefanwille could you help me out with this one?

I want to get the hash coming out of the JSON file to be displayed in this new ERB file...
get '/my_characters' do
 @title = 'My Characters'
 @characterlist = ## json to hash contents here ##
  erb :my_characters
end

A bit further up in the main app file (is that called the controller file?) is where I read the JSON file into the hash:
def read_characters(my_characters)
  readfile = File.read("characters.json")
  return JSON.parse(readfile)
end

I have been trying around with the variables/arguments my_characters and readfile but both either don't work or return errors. I also tried to make readfile global, to no avail :(

**Comment by stefanwille** [comment]
Sure!

So, first you should remove the `my_characters` parameter from `read_characters()` - it serves no purpose, I think it's a leftover from an older change. Like so:

``` ruby
def read_characters()
  readfile = File.read("characters.json")
  return JSON.parse(readfile)
end
```

After you have done that, you can call the function `read_characters()` in your Sinatra action:

``` ruby
get '/my_characters' do
  @title = 'My Characters'
  @characterlist = read_characters()
  erb :my_characters
end
```

Isn't this nice? :smile: 

Now you can render your characters in `my_characters.html.erb` to HTML. For example:

``` html
<ul>
  <% @characterlist.each do |character|  %>
    <li>
      Name: <%= character['name'] %>
    </li>    
  <% end %>
</ul>
```

**Comment by supernoir** [comment]
It works! So awesome! Thank you so much :)

![screenshot](https://cloud.githubusercontent.com/assets/13038195/8878410/17141012-322b-11e5-8ed5-f69e7398e076.png)
![the-hills](https://cloud.githubusercontent.com/assets/13038195/8878409/171405a4-322b-11e5-89cf-3a5a1d24baa7.gif)

**Comment by stefanwille** [comment]
cooool :+1:
